services:
 app:
  build:
   context: .
   dockerfile: Dockerfile
  container_name: laravel-app
  restart: unless-stopped
  working_dir: /var/www
  volumes:
  - .:/var/www
  depends_on:
  - db
  - redis
  ports:
  - "8000:8000"
  environment:
   APP_NAME: Katolec
   APP_ENV: production
   APP_KEY: base64:qGR1Yy3aE3kAeBkeNY5CNwUddbvMcvC7a01jLhOjkLE=
   APP_DEBUG: "false"
   APP_TIMEZONE: UTC
   APP_URL: https://simpro.shop
   DB_CONNECTION: mysql
   DB_HOST: db
   DB_PORT: 3306
   DB_DATABASE: u952929673_produksi
   DB_USERNAME: u952929673_produksi
   DB_PASSWORD: Simpro101
   SESSION_DRIVER: database
   CACHE_STORE: database
   QUEUE_CONNECTION: database
   REDIS_CLIENT: phpredis
   REDIS_HOST: redis
   REDIS_PASSWORD: null
   REDIS_PORT: 6379

 db:
  image: mysql:8
  container_name: mysql-db
  restart: unless-stopped
  environment:
   MYSQL_DATABASE: u952929673_produksi
   MYSQL_USER: u952929673_produksi
   MYSQL_PASSWORD: Simpro101
   MYSQL_ROOT_PASSWORD: rootpassword
  volumes:
  - db_data:/var/lib/mysql

 redis:
  image: redis:alpine
  container_name: redis-server
  restart: unless-stopped

 phpmyadmin:
  image: phpmyadmin/phpmyadmin
  restart: unless-stopped
  ports:
  - "8080:80"
  environment:
   PMA_HOST: db
   MYSQL_ROOT_PASSWORD: rootpassword

volumes:
 db_data:
